/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.ui;

import com.mycompany.mavenproject1.HibernateUtil;
import com.mycompany.mavenproject1.database.repository.MaterialDAO;
import com.mycompany.mavenproject1.database.repository.MaterialReporteDAO;
import com.mycompany.mavenproject1.tablas.TodosMaterial;
import com.mycompany.mavenproject1.tablas.TodosMaterialReporte;
import java.awt.Color;

/**
 *
 * @author Sebas
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    MaterialReporteDAO mr;
    MaterialDAO md;

    public AdminPanel() {
        initComponents();
        this.setBounds(0, 0, 800, 600);
        this.setBackground(Color.LIGHT_GRAY);
        this.mr = new MaterialReporteDAO(HibernateUtil.getSessionFactory());
        this.md = new MaterialDAO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBorrarInsumos = new javax.swing.JButton();
        btnBorrarMateriales = new javax.swing.JButton();

        btnBorrarInsumos.setText("Borrar Insumos");
        btnBorrarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarInsumosActionPerformed(evt);
            }
        });

        btnBorrarMateriales.setText("Borrar Materiales");
        btnBorrarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarMaterialesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnBorrarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnBorrarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarInsumosActionPerformed
        // TODO add your handling code here:

        Runnable mRunnable = () -> {

            Cargando c = new Cargando("Limipiando");
            c.setVisible(true);
            //mr.deleteAll();
            md.deleteAll();
            EntradaPanel.paths.clear();
            TodosMaterialReporte.regargarPanel();
            TodosMaterialReporte.cargarDatos();
            TodosMaterial.cargarDatos();
            c.dispose();

        };
        Thread miHilo = new Thread(mRunnable);
        miHilo.start();


    }//GEN-LAST:event_btnBorrarInsumosActionPerformed

    private void btnBorrarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarMaterialesActionPerformed
        // TODO add your handling code here:
        Runnable mRunnable = () -> {

            Cargando c = new Cargando("Limipiando");
            c.setVisible(true);
            mr.deleteAll();
            //md.deleteAll();
            EntradaPanel.paths.clear();
            TodosMaterialReporte.regargarPanel();
            TodosMaterialReporte.cargarDatos();
            TodosMaterial.cargarDatos();
            c.dispose();

        };
        Thread miHilo = new Thread(mRunnable);
        miHilo.start();
    }//GEN-LAST:event_btnBorrarMaterialesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarInsumos;
    private javax.swing.JButton btnBorrarMateriales;
    // End of variables declaration//GEN-END:variables
}
