/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.ui;

import com.mycompany.mavenproject1.utils.FileUtils;
import com.mycompany.mavenproject1.utils.InsumosUtils;
import com.mycompany.mavenproject1.utils.ValidarUtils;
import com.mycompany.mavenproject1.database.model.Cliente;
import com.mycompany.mavenproject1.database.DAO.ClienteDAO;
import com.mycompany.mavenproject1.database.DAO.MaterialReporteDAO;
import com.mycompany.mavenproject1.database.DAO.ReporteDAO;
import com.mycompany.mavenproject1.database.model.Reporte;
import com.mycompany.mavenproject1.tablas.TodosMaterial;
import com.mycompany.mavenproject1.tablas.TodosMaterialReporte;
import com.mycompany.mavenproject1.utils.HibernateUtil;
import com.mycompany.mavenproject1.utils.PdfUtils;
import com.mycompany.mavenproject1.utils.ValidarFacturaUtils;
import java.awt.Color;
import java.awt.Cursor;
import java.io.IOException;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class EntradaPanel extends javax.swing.JPanel {

    //var pathInsumos;
    public static Map<String, String> paths;
    private Cliente cliente;
    private ReporteDAO reporteDAO;
    //var pathListadoFacturas;

    /**
     * Creates new form Panel1
     */
    public EntradaPanel() {
        initComponents();
        cargarClientes();
        this.setBounds(0, 0, 800, 600);
        this.setBackground(Color.LIGHT_GRAY);
        paths = new HashMap<>();
        cliente = (Cliente) this.comboCliente.getSelectedItem();
        reporteDAO = new ReporteDAO(HibernateUtil.getSessionFactory());
    }

    private void cargarClientes() {
        ClienteDAO clienteDAO = new ClienteDAO();
        var clientes = clienteDAO.readAll();
        clientes.stream().forEach(x -> this.comboCliente.addItem(x));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cargarReporteProduccion = new javax.swing.JButton();
        cargarInsumos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        reporteInsumos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        reporteCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cargarFacturas = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Reporte de producción");

        cargarReporteProduccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargarReporteProduccion.setText("Cargar");
        cargarReporteProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarReporteProduccionActionPerformed(evt);
            }
        });

        cargarInsumos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargarInsumos.setText("Cargar");
        cargarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarInsumosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Insumos");

        comboCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboClienteItemStateChanged(evt);
            }
        });
        comboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClienteActionPerformed(evt);
            }
        });

        reporteInsumos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reporteInsumos.setText("Generar");
        reporteInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteInsumosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Reporte clientes");

        reporteCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reporteCliente.setText("Generar");
        reporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteClienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Reporte insumos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Reportes");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Facturas");

        cargarFacturas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargarFacturas.setText("Cargar");
        cargarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cargarReporteProduccion)
                            .addComponent(cargarInsumos)
                            .addComponent(cargarFacturas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap(321, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(reporteCliente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(reporteInsumos))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargarReporteProduccion)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargarInsumos)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reporteInsumos)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reporteCliente)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarFacturas)
                            .addComponent(jLabel5))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarReporteProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarReporteProduccionActionPerformed
        // TODO add your handling code here:
        var path = FileUtils.cargarData("Cargar Reporte De Produccion");
        if (path != null) {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));

            getPaths().put("RP", path);
            ValidarUtils validar = new ValidarUtils(path);
            if (validar.validar()) {
                TodosMaterialReporte.regargarPanel();
                TodosMaterialReporte.cargarDatos();
                Reporte r = new Reporte();
                r.setRuta(path);
                reporteDAO.deleteAll();
                reporteDAO.create(r);
                MaterialReporteDAO materialReporteDAO=new MaterialReporteDAO(HibernateUtil.getSessionFactory());
                materialReporteDAO.deleteAll();
                FormMaterialReporte.cargarDatos();
                JOptionPane.showMessageDialog(null, "Reporte de produccion cargado correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error");

            }
            //

            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }

    }//GEN-LAST:event_cargarReporteProduccionActionPerformed

    private void cargarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarInsumosActionPerformed
        // TODO add your handling code here:
        var path = FileUtils.cargarData(true, "Cargar Insumos");
        if (path != null) {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));

            getPaths().put("IN", path);
            InsumosUtils insumosUtils = new InsumosUtils(paths, (Cliente) comboCliente.getSelectedItem());
            insumosUtils.saveAllInsumos(cliente.getRuc());
            TodosMaterial.cargarDatos();
            Reporte reporte = reporteDAO.read();
            if (reporte != null) {
                TodosMaterialReporte.regargarPanel();
            }
            JOptionPane.showMessageDialog(null, "Listado de insumos cargado correctamente");

            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        } else {
            ///
        }

    }//GEN-LAST:event_cargarInsumosActionPerformed

    private void reporteInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteInsumosActionPerformed
        // TODO add your handling code here:
        Reporte reporte = reporteDAO.read();
        if (reporte == null) {
            JOptionPane.showMessageDialog(null, "Cargue el reporte de produccion");

        } else {
            JDialog dialog = new JDialog();
            dialog.setTitle("Generar Reporte De Insumos");
            dialog.getContentPane().add(new FormInformeFinal(cliente, "insumos"));
            dialog.setSize(400, 150);
            dialog.setModal(true);
            dialog.setVisible(true);
        }


    }//GEN-LAST:event_reporteInsumosActionPerformed

    private void comboClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboClienteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClienteItemStateChanged

    private void comboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClienteActionPerformed
        // TODO add your handling code here:
        cliente = (Cliente) comboCliente.getSelectedItem();
    }//GEN-LAST:event_comboClienteActionPerformed

    private void reporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteClienteActionPerformed
        // TODO add your handling code here:
        Reporte reporte = reporteDAO.read();
        if (reporte == null && cliente.getNombre().contains("CRA")) {
            JOptionPane.showMessageDialog(null, "Cargue el reporte de produccion");

        } else {
            
            JDialog dialog = new JDialog();
            dialog.setTitle("Generar Reporte De Cliente");
            dialog.getContentPane().add(new FormInformeFinal(cliente, "cliente"));
            dialog.setSize(400, 150);
            dialog.setModal(true);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_reporteClienteActionPerformed

    private void cargarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFacturasActionPerformed
        // TODO add your handling code here:
        PdfUtils pdfUtils=new PdfUtils(cliente);
        try {
            pdfUtils.cargarPDFs();
        } catch (IOException ex) {
            Logger.getLogger(EntradaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cargarFacturasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarFacturas;
    private javax.swing.JButton cargarInsumos;
    private javax.swing.JButton cargarReporteProduccion;
    private javax.swing.JComboBox<Cliente> comboCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton reporteCliente;
    private javax.swing.JButton reporteInsumos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the paths
     */
    public Map<String, String> getPaths() {
        return paths;
    }

    /**
     * @param paths the paths to set
     */
    public void setPaths(Map<String, String> paths) {
        this.paths = paths;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

}
