/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.ui;

import com.mycompany.mavenproject1.FileUtils;
import com.mycompany.mavenproject1.InsumosUtils;
import com.mycompany.mavenproject1.database.model.Cliente;
import com.mycompany.mavenproject1.database.repository.ClienteDAO;
import java.awt.Color;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class EntradaPanel extends javax.swing.JPanel {

    //var pathInsumos;
    public static Map<String, String> paths;
    private Cliente cliente;
    //var pathListadoFacturas;

    /**
     * Creates new form Panel1
     */
    public EntradaPanel() {
        initComponents();
        cargarClientes();
        this.setBounds(0, 0, 800, 600);
        this.setBackground(Color.LIGHT_GRAY);
        paths = new HashMap<>();
        cliente=(Cliente) this.comboCliente.getSelectedItem();
    }

    private void cargarClientes() {
        ClienteDAO clienteDAO = new ClienteDAO();
        var clientes = clienteDAO.readAll();
        clientes.stream().forEach(x -> this.comboCliente.addItem(x));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cargarReporteProduccion = new javax.swing.JButton();
        cargarInsumos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        cargarInsumos2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Reporte de producción");

        cargarReporteProduccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargarReporteProduccion.setText("Cargar");
        cargarReporteProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarReporteProduccionActionPerformed(evt);
            }
        });

        cargarInsumos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargarInsumos.setText("Cargar");
        cargarInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarInsumosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Insumos");

        comboCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboClienteItemStateChanged(evt);
            }
        });
        comboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClienteActionPerformed(evt);
            }
        });

        cargarInsumos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargarInsumos2.setText("Generar");
        cargarInsumos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarInsumos2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Reporte Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargarReporteProduccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cargarInsumos, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cargarInsumos2)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargarReporteProduccion)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargarInsumos)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargarInsumos2)
                            .addComponent(jLabel6))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarReporteProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarReporteProduccionActionPerformed
        // TODO add your handling code here:
        var path = FileUtils.cargarData();
        if (path != null) {
            JOptionPane.showMessageDialog(null, "Reporte de produccion cargado correctamente");
            getPaths().put("RP", path);

        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }

    }//GEN-LAST:event_cargarReporteProduccionActionPerformed

    private void cargarInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarInsumosActionPerformed
        // TODO add your handling code here:
        var path = FileUtils.cargarData(true);
        if (path != null) {

            JOptionPane.showMessageDialog(null, "Listado de insumos cargado correctamente");
            getPaths().put("IN", path);
            InsumosUtils insumosUtils = new InsumosUtils(this.paths, (Cliente) this.comboCliente.getSelectedItem());
            insumosUtils.saveAllInsumos();

        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }

    }//GEN-LAST:event_cargarInsumosActionPerformed

    private void cargarInsumos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarInsumos2ActionPerformed
        // TODO add your handling code here:
        if (this.paths.get("RP") == null) {
            JOptionPane.showMessageDialog(null, "Cargue el reporte de produccion");

        } else {
            JDialog dialog = new JDialog();
            dialog.setTitle("Generar");
            dialog.getContentPane().add(new FormInformeFinal(this.paths.get("RP"),cliente));
            dialog.setSize(400, 150);
            dialog.setVisible(true);
        }


    }//GEN-LAST:event_cargarInsumos2ActionPerformed

    private void comboClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboClienteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClienteItemStateChanged

    private void comboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClienteActionPerformed
        // TODO add your handling code here:
        cliente=(Cliente) comboCliente.getSelectedItem();
    }//GEN-LAST:event_comboClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarInsumos;
    private javax.swing.JButton cargarInsumos2;
    private javax.swing.JButton cargarReporteProduccion;
    private javax.swing.JComboBox<Cliente> comboCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the paths
     */
    public Map<String, String> getPaths() {
        return paths;
    }

    /**
     * @param paths the paths to set
     */
    public void setPaths(Map<String, String> paths) {
        this.paths = paths;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

}
