/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.ui;

import com.mycompany.mavenproject1.FileUtils;
import com.mycompany.mavenproject1.InformeClientesUtils;
import com.mycompany.mavenproject1.InformeInsumosUtils;
import com.mycompany.mavenproject1.database.model.Cliente;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Sebas
 */
public class FormInformeFinal extends javax.swing.JPanel {

    /**
     * Creates new form GeneralPanelç
     */
    private JDateChooser dateChooser;
    private JDateChooser dateChooser2;
    private Cliente cliente;

    public FormInformeFinal(String path, Cliente cliente, String tipo) {
        initComponents();

        this.setBackground(Color.LIGHT_GRAY);

        JLabel label1 = new JLabel("Desde");
        dateChooser = new JDateChooser();
        dateChooser.setBounds(10, 20, 150, 30);
        label1.setBounds(10, 0, 150, 30);

        this.add(label1);
        this.add(dateChooser);
        JLabel label2 = new JLabel("Hasta");

        dateChooser2 = new JDateChooser();
        dateChooser2.setBounds(200, 20, 150, 30);
        label2.setBounds(200, 0, 150, 30);
        this.add(label2);
        this.add(dateChooser2);

        JButton filterButton = new JButton("Filtrar");
        filterButton.setBounds(150, 70, 150, 30);

        this.add(filterButton);
        if (tipo.equals("cliente")) {
            filterButton.addActionListener((ActionEvent e) -> {
                Date inicio = dateChooser.getDate();

                Date fin = dateChooser2.getDate();
                Runnable mRunnable = () -> {
                    Cargando c = new Cargando("Generando");
                    c.setVisible(true);
                    InformeClientesUtils ifu = new InformeClientesUtils(path, FileUtils.saveDataOne(), cliente);
                    ifu.generarInforme(inicio, quitarHora(fin));
                    c.dispose();
                };
                Thread miHilo = new Thread(mRunnable);
                miHilo.start();
            });
        } else {
            filterButton.addActionListener((ActionEvent e) -> {
                Date inicio = dateChooser.getDate();

                Date fin = dateChooser2.getDate();
                Runnable mRunnable = () -> {
                    Cargando c = new Cargando("Generando");
                    c.setVisible(true);
                    InformeInsumosUtils ifu = new InformeInsumosUtils(path, FileUtils.saveDataOne(), cliente);
                    ifu.generarInforme(inicio, quitarHora(fin));
                    c.dispose();
                };
                Thread miHilo = new Thread(mRunnable);
                miHilo.start();
            });
        }
    }

    public static Date quitarHora(Date fecha) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(fecha);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);

        return cal.getTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
