/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.ui;

import com.mycompany.mavenproject1.database.model.Cliente;
import com.mycompany.mavenproject1.database.model.Material;
import com.mycompany.mavenproject1.database.DAO.ClienteDAO;
import com.mycompany.mavenproject1.database.DAO.MaterialDAO;

import java.awt.Color;
import java.awt.Window;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sebas
 */
public class FormMaterial extends javax.swing.JPanel {

    /**
     * Creates new form Panel3
     */
    ClienteDAO cr = new ClienteDAO();
    MaterialDAO mr = new MaterialDAO();
    List<Cliente> clientes;
    private Cliente cliente;

    public FormMaterial() {
        initComponents();
        // txtPDesperdicio.setEnabled(false);

        this.setBackground(Color.LIGHT_GRAY);

        cargarDatos();

        //this.comboCliente.
    }

    public FormMaterial(String codigo,Cliente cliente) {
        initComponents();
        //txtPDesperdicio.setEnabled(false);

        this.setBackground(Color.LIGHT_GRAY);
        this.btnGuardar.setText("Actualizar");
        cargarDatos();
        Material material = this.mr.readByCodigo(codigo,cliente.getRuc());
        this.comboCliente.setSelectedItem(material.getCliente());
        this.txtCodigo.setText(material.getCodigo());

        this.txtDescripcion.setText(material.getDescripcion());
        this.txtTipoUnidad.setText(String.valueOf(material.getTipoUnidad()));
        this.txtSubpartida.setText(material.getSubpartida());
        this.txtPDesperdicio.setText(material.getPorcentajeDesperdicio() != null ? String.valueOf(material.getPorcentajeDesperdicio()) : "");
        this.txtPMerma.setText(material.getPorcentajeMerma() != null ? String.valueOf(material.getPorcentajeMerma()) : "");
        this.txtSaldos.setText(material.getSaldoInsumo() != null ? String.valueOf(material.getSaldoInsumo()) : "");
        this.txtCConsumo.setText(material.getCoeficienteConsumo() != null ? String.valueOf(material.getCoeficienteConsumo()) : "");
        this.bolDesperdicio.setSelected(material.getCalculaDesperdicio() != null ? material.getCalculaDesperdicio() : false);
        this.bolFormula.setSelected(material.getAplicaFormula() != null ? material.getAplicaFormula() : false);

        //this.comboCliente.
    }

    private void cargarDatos() {

        this.clientes = cr.readAll();
        this.clientes.stream().forEach(x -> this.comboCliente.addItem(x));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtSubpartida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipoUnidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSaldos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPMerma = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCConsumo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPDesperdicio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bolDesperdicio = new javax.swing.JCheckBox();
        bolFormula = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        comboCliente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cliente");

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSubpartida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Subpartida");

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Descripción");

        txtTipoUnidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tipo unidad");

        txtSaldos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSaldos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldosKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Saldo de insumos por regularizar");

        txtPMerma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPMerma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPMermaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Porcentaje de merma");

        txtCConsumo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCConsumo.setEnabled(false);
        txtCConsumo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCConsumoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Coeficiente de consumo");

        txtPDesperdicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPDesperdicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPDesperdicioKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Porcentaje de desperdicio");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("No calcula desperdicio");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Aplica formula");

        bolDesperdicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bolDesperdicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bolDesperdicioStateChanged(evt);
            }
        });

        bolFormula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bolFormula.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bolFormulaStateChanged(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Código");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel11)
                                .addComponent(jLabel4)
                                .addComponent(txtCodigo)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPMerma, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCConsumo))
                                            .addGap(40, 40, 40))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bolDesperdicio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bolFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPDesperdicio)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel7))
                                        .addComponent(jLabel2))
                                    .addGap(13, 13, 13))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtSubpartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnGuardar)
                        .addGap(80, 80, 80)
                        .addComponent(btnCancelar)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubpartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPMerma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPDesperdicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bolFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bolDesperdicio)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //var cliente = this.comboCliente.getSelectedItem();
        var codigo = this.txtCodigo.getText();
        var subpartida = this.txtSubpartida.getText();
        var descripcion = this.txtDescripcion.getText();
        var tipoUnidad = this.txtTipoUnidad.getText();
        var saldos = this.txtSaldos.getText();
        var porcentajeMerma = this.txtPMerma.getText();
        var coeficienteConsumo = this.txtCConsumo.getText();
        var porcentajeDesperdicio = this.txtPDesperdicio.getText();
        var calculaDesperdicio = this.bolDesperdicio;
        var aplicaFormula = this.bolFormula;
        var cliente=clientes.get(this.comboCliente.getSelectedIndex());
        Material mat = new Material();
        if (!codigo.isEmpty()) {
            mat.setCodigo(codigo);
        } else {
            mostrarMensajeVacio("codigo");

            return;
        }
        if (!subpartida.isEmpty()) {
            mat.setSubpartida(subpartida);

        } else {
            mostrarMensajeVacio("subpartida");
            return;

        }
        if (!descripcion.isEmpty()) {
            mat.setDescripcion(descripcion);

        } else {
            mostrarMensajeVacio("descripcion");
            return;
        }

        if (!saldos.isEmpty()) {
            mat.setSaldoInsumo(new BigDecimal(saldos));
        }

        if (!porcentajeMerma.isEmpty()) {
            mat.setPorcentajeMerma(new BigDecimal(porcentajeMerma));

        }

        mat.setCliente(cliente);
        if (aplicaFormula.isSelected() == true) {
            if (!coeficienteConsumo.isEmpty()) {
                mat.setCoeficienteConsumo(new BigDecimal(coeficienteConsumo));
            } else {
                mostrarMensajeVacio("coeficiente de consumo");

            }
        }
        if (calculaDesperdicio.isSelected() == false) {
            if (!porcentajeDesperdicio.isEmpty()) {
                mat.setPorcentajeDesperdicio(new BigDecimal(porcentajeDesperdicio));

            } else {
                mostrarMensajeVacio("desperdicio");
                return;
            }
        }

        if (!tipoUnidad.isEmpty()) {
            mat.setTipoUnidad(tipoUnidad);

        } else {
            mostrarMensajeVacio("tipo de unidad");
            return;
        }
        mat.setCalculaDesperdicio(calculaDesperdicio.isSelected());
        mat.setAplicaFormula(aplicaFormula.isSelected());

        if (this.btnGuardar.getText().equals("Actualizar")) {
            if (mr.update(mat)) {
                JOptionPane.showMessageDialog(null, "Actualizado correctamente");

            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error");

            }

        } else {
            var materialExistente=mr.readByCodigo(codigo,cliente.getRuc());
           
            if (materialExistente==null) {
                if (mr.create(mat)) {
                    JOptionPane.showMessageDialog(null, "Creado correctamente");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un error");

                }
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe el material");

            }

        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);
        window.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed
    public void mostrarMensajeVacio(String val) {
        JOptionPane.showMessageDialog(null, val + " esta vacio");
    }
    private void txtSaldosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldosKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key == 46;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldosKeyTyped

    private void txtPMermaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPMermaKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key == 46;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPMermaKeyTyped

    private void txtCConsumoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCConsumoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key == 46;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCConsumoKeyTyped

    private void txtPDesperdicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPDesperdicioKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key == 46;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPDesperdicioKeyTyped

    private void bolDesperdicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bolDesperdicioStateChanged
        // TODO add your handling code here:
        if (bolDesperdicio.isSelected()) {
            txtPDesperdicio.setEnabled(false);
        } else {
            txtPDesperdicio.setEnabled(true);

        }
    }//GEN-LAST:event_bolDesperdicioStateChanged
    private void limpiar() {
        this.txtCodigo.setText("");
        this.txtSubpartida.setText("");
        this.txtDescripcion.setText("");
        this.txtTipoUnidad.setText("");
        this.txtSaldos.setText("");
        this.txtPMerma.setText("");
        this.txtCConsumo.setText("");
        this.txtPDesperdicio.setText("");
        this.bolDesperdicio.setSelected(false);
        this.bolFormula.setSelected(false);
    }
    private void bolFormulaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bolFormulaStateChanged
        // TODO add your handling code here:
        if (bolFormula.isSelected()) {
            txtCConsumo.setEnabled(true);
        } else {
            txtCConsumo.setEnabled(false);

        }
    }//GEN-LAST:event_bolFormulaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bolDesperdicio;
    private javax.swing.JCheckBox bolFormula;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Cliente> comboCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCConsumo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPDesperdicio;
    private javax.swing.JTextField txtPMerma;
    private javax.swing.JTextField txtSaldos;
    private javax.swing.JTextField txtSubpartida;
    private javax.swing.JTextField txtTipoUnidad;
    // End of variables declaration//GEN-END:variables
}
